# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4cb05c8c75865ebb1387d999e9d5c4f14ec8a132ea1136fd27b51da9388a86d859dcdcc1cc7b18b884ce3212236c3d7e708b4a36f57500edf0807ecb99b68c9

test:
  secret_key_base: 6cd4244b10f78d85f6892cb51586006cca5e1a9e700292850a9d6476624764b3db1fc61417e9921a324524c9bbd0314d49a003d5f760f1388c83bdacaad0d1d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
